version: '3.8'

services:
  lodestone-core:
    image: dizzlehd/lodestone-core:latest
    container_name: lodestone-core
    restart: unless-stopped
    ports:
      - "16662:16662"
    volumes:
      - lodestone-data:/home/user/.lodestone

  lodestone-dashboard:
    image: dizzlehd/lodestone-dashboard:latest
    container_name: lodestone-dashboard
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - lodestone-core

volumes:
  lodestone-data:
